[package]
name = "rtlsdr_sys"
version = "1.0.0"
authors = ["Mick Koch <mick@kochm.co>"]
license = "GPLv2"
build = "build.rs"

[dependencies]
libc = "^0.2.8"

[build-dependencies]
pkg-config = "^0.3.6"
